# Generated by Django 2.2.8 on 2020-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('picture', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'classify',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名')),
                ('permission', models.CharField(max_length=100, verbose_name='权限')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名')),
                ('parent_menu', models.CharField(max_length=50, verbose_name='父菜单')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('gender', models.SmallIntegerField(verbose_name='性别')),
                ('face_info', models.CharField(blank=True, max_length=10000, null=True, verbose_name='人脸特征')),
                ('picture', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='密码')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否禁用')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='RuleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, verbose_name='用户')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('rule', models.ForeignKey(on_delete=True, to='main.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='权限名')),
                ('type', models.CharField(max_length=50, verbose_name='权限类型')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('sys_menu', models.ForeignKey(on_delete=True, to='main.SysMenu')),
            ],
            options={
                'db_table': 'premission',
            },
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('article', models.ForeignKey(on_delete=True, to='main.Article', verbose_name='评论文章')),
                ('user_info', models.ForeignKey(on_delete=True, to='main.UserInfo', verbose_name='评论人')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(on_delete=True, to='main.Classify', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_info',
            field=models.ForeignKey(on_delete=True, to='main.UserInfo', verbose_name='作者'),
        ),
    ]
